name: defectdojo import report
description: 'a github action that sends scan reports to a DefectDojo instance'
inputs:
  defectdojo-url:
    description: the url of your defectdojo instance
    required: true
  defectdojo-username:
    description: the username to login into your defectdojo instance
    required: true
  defectdojo-password:
    description: the password to login into your defectdojo instance
    required: true
  defectdojo-product-type:
    description: the defectdojo product type that the scan result relates to
    required: true
  defectdojo-product:
    description: the defectdojo product that the scan result relates to
    required: true
  defectdojo-environment-type:
    description: the defectdojo environment type that the scan result relates to
    required: true
  defectdojo-scan-type:
    description: the defectdojo scan type that the scan result relates to
    required: true
  defectdojo-engagement-name:
    description: the defectdojo engagement name that the scan result relates to
    required: true
  scan-results-file-name:
    description: the file name of the scan result to be uploaded are stored
    required: true
  client-certificate-file-path:
    description: the file path for a client side certificate if required
    required: false
  client-key-file-path:
    description: the file path for a client side private key if required
    required: false
runs:
  using: docker
  image: docker://ghcr.io/portswigger-cloud/defectdojo-utils:v1.0.1
  entrypoint: /usr/defectdojo-utils/src/import_scan_results.py
  env:
    DEFECT_DOJO_URL: ${{ inputs.defectdojo-url }}
    DEFECT_DOJO_USERNAME: ${{ inputs.defectdojo-username }}
    DEFECT_DOJO_PASSWORD: ${{ inputs.defectdojo-password }}
    DEFECT_DOJO_PRODUCT_TYPE: ${{ inputs.defectdojo-product-type }}
    DEFECT_DOJO_PRODUCT: ${{ inputs.defectdojo-product }}
    DEFECT_DOJO_ENVIRONMENT_TYPE: ${{ inputs.defectdojo-environment-type }}
    DEFECT_DOJO_SCAN_TYPE: ${{ inputs.defectdojo-scan-type }}
    DEFECT_DOJO_ENGAGEMENT_NAME: ${{ inputs.defectdojo-engagement-name }}
    SCAN_RESULTS_FILE_PATH: /github/workspace/${{ inputs.scan-results-file-name }}
    CLIENT_CERTIFICATE_FILE_PATH: ${{ inputs.client-certificate-file-path }}
    CLIENT_KEY_FILE_PATH: ${{ inputs.client-key-file-path }}
branding:
  icon: 'shield'
  color: 'orange'
